import { CodeLibelle } from "./code-libelle";


export class Ennemi{
    "nom":string;
    "type":string;
};

export class EnnemiType{
    "code":string;
    "libelle":string;
    "zoneCode":string;
};

export class Mob{
    "zone":string
    "code":string;
    "libelle":string;
    "vie" : number;
    "armure":number;
    "degats":string;
    "attaque":number;
    "parade":number;
    "experience":number;
    "informations":string;
}

export class EnnemiHelper{
    
    static  getAllZone():Array<CodeLibelle>
    {
        return [{
            code:"foret",
            libelle:"Forêt"
        },
        {
            code:"foret-dangereuse",
            libelle:"Forêt Dangereuse"
        },
        {
            code:"desert",
            libelle:"Désert"
        },
        {
            code:"grottes",
            libelle:"Grottes"
        },
        {
            code:"humain",
            libelle:"Humains"
        },
        {
            code:"mer",
            libelle:"Milieu aquatique"
        },
        {
            code:"montagne",
            libelle:"Montagne"
        },
        {
            code:"souterrain",
            libelle:"Souterrain"
        },
        {
            code:"terre",
            libelle:"Terres Sauvage"
        },
        {
            code:"terre-dangereux",
            libelle:"Terres Sauvage Dangereuses"
        },
        {
            code:"urbain",
            libelle:"Urbain"
        },
        {
            code:"montagne",
            libelle:"Montagne"
        },
        {
            code:"givre",
            libelle:"Givre"
        },
        {
            code:"jungle",
            libelle:"Jungle"
        }];
    }  

    static getAllEnnemiType() : Array<EnnemiType>
    {
        return [
        {
            code:"coccinelle",
            libelle:"Coccinelle berserk",
            zoneCode:"foret"
        },
        {
            code:"brigant",
            libelle:"1 brigant de base",
            zoneCode:"foret"
        },
        {
            code:"rat-geant",
            libelle:"1 rat géant affamés",
            zoneCode:"foret"
        },
        {
            code:"bouc",
            libelle:"Bouc en colère",
            zoneCode:"terre"
        },
        {
            code:"coyote",
            libelle:"1 coyote affamé",
            zoneCode:"terre"
        },
        {
            code:"troll-geant",
            libelle:"1 Troll géant maladrois",
            zoneCode:"terre"
        },
        ]
    }

    static getAllEnnemiTypeFromZone(zone:string) : Array<EnnemiType>
    {
        return this.getAllEnnemiType().filter(x=>x.zoneCode == zone);
    }

    static getMobDesert(): Mob[]{
        return [
            {
                code:("Scarabée du désert").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Scarabée du désert",
                zone:"désert",
                attaque:15,
                parade:0,
                vie:0,
                informations:"On doit réussir une épreuve d’adresse pour l’écraser",
                degats:"1",
                armure:0,
                experience:2,
            },
            {
                code:("Scorpion du désert").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Scorpion du désert",
                zone:"désert",
                attaque:12,
                parade:0,
                vie:2,
                informations:"Poison : -1 Stats",
                degats:"1D-1",
                armure:1,
                experience:4,
            },
            {
                code:("Fennec").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Fennec",
                zone:"désert",
                attaque:10,
                parade:3,
                vie:6,
                armure:1,
                degats:"1D",
                experience:6,
                informations:"",
            },
            {
                code:("Cobra").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Cobra",
                zone:"désert",
                attaque:8,
                parade:3,
                vie:8,
                armure:1,
                degats:"1D+1",
                experience:8,
                informations:"Poison : -1 Stats",
            },
            {
                code:("Momie").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Momie",
                zone:"désert",
                attaque:8,
                parade:5,
                vie:18,
                armure:1,
                degats:"1D+1",
                experience:10,
                informations:"",
            },
            {
                code:("Vautour").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Vautour",
                zone:"désert",
                attaque:8,
                parade:14,
                vie:8,
                armure:1,
                degats:"1D+1",
                experience:10,
                informations:"",
            },
            {
                code:("Homme des sables").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Homme des sables",
                zone:"désert",
                attaque:8,
                parade:8,
                vie:20,
                armure:1,
                degats:"1D+3",
                experience:12,
                informations:"",
            },
            {
                code:("Dromadaire enragé").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Dromadaire enragé",
                zone:"désert",
                attaque:7,
                parade:5,
                vie:30,
                armure:2,
                degats:"1D+5",
                experience:15,
                informations:"",
            },
            {
                code:("Taupe géante").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Taupe géante",
                zone:"désert",
                attaque:9,
                parade:7,
                vie:20,
                armure:1,
                degats:"1D+3",
                experience:15,
                informations:"",
            },
            {
                code:("Marchand de sable").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Marchand de sable",
                zone:"désert",
                attaque:8,
                parade:8,
                vie:20,
                armure:1,
                degats:"1D+3",
                experience:12,
                informations:"1D 100 pièce or",
            },
            {
                code:("Tigre à dents de sable").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Tigre à dents de sable",
                zone:"désert",
                attaque:9,
                parade:8,
                vie:18,
                armure:1,
                degats:"1D+3",
                experience:18,
                informations:"",
            },
            {
                code:("Vieux tigre à dents de sable").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Vieux tigre à dents de sable",
                zone:"désert",
                attaque:10,
                parade:9,
                vie:25,
                armure:1,
                degats:"1D+5",
                experience:22,
                informations:"A 50% => 1/4 chance appeler un jeune en renfort",
            },
            {
                code:("Garde de la pyramide").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Garde de la pyramide",
                zone:"désert",
                attaque:11,
                parade:9,
                vie:22,
                armure:4,
                degats:"1D+3",
                experience:25,
                informations:"",
            },
            {
                code:("Grand requin des sables").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Grand requin des sables",
                zone:"désert",
                attaque:12,
                parade:10,
                vie:30,
                armure:2,
                degats:"1D+4",
                experience:28,
                informations:"",
            },
            {
                code:("Pharaon").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Pharaon",
                zone:"désert",
                attaque:13,
                parade:10,
                vie:30,
                armure:3,
                degats:"1D+4",
                experience:30,
                informations:"1D6 pierre précieuse",
            },
            {
                code:("Phénix").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Phénix",
                zone:"désert",
                attaque:10,
                parade:15,
                vie:40,
                armure:2,
                degats:"1D+5",
                experience:40,
                informations:"1/2 chance de repop quand mort",
            },
            {
                code:("Elephant furieux").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Elephant furieux",
                zone:"désert",
                attaque:8,
                parade:6,
                vie:50,
                armure:2,
                degats:"2D+4",
                experience:45,
                informations:"Impossible à parer",
            },
            {
                code:("Statue d'un dieu").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Statue d'un dieu",
                zone:"désert",
                attaque:9,
                parade:7,
                vie:45,
                armure:4,
                degats:"2D+3",
                experience:50,
                informations:"arme en pierre",
            },
            {
                code:("Ver géant des sables").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Ver géant des sables",
                zone:"désert",
                attaque:8,
                parade:6,
                vie:50,
                armure:4,
                degats:"2D+3",
                experience:60,
                informations:"Attaque furtive",
            },
            {
                code:("Sphinx géant").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Sphinx géant",
                zone:"désert",
                attaque:8,
                parade:5,
                vie:60,
                armure:5,
                degats:"2D+7",
                experience:80,
                informations:"Immunisé magie",
            },
        ]
    }

    static getMobTerreSauvage(): Mob[]{
        return [
            {
                code:("Coyote affamé").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Coyote affamé",
                zone:"terre-sauvage",
                attaque:10,
                parade:4,
                vie:8,
                armure:1,
                degats:"1D",
                experience:4,
                informations:"",
            },
            {
                code:("Scorpion").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Scorpion",
                zone:"terre-sauvage",
                attaque:12,
                parade:0,
                vie:2,
                armure:0,
                degats:"1D-1",
                experience:5,
                informations:"Poison : -1 Stats",
            },
            {
                code:("Cochon mutant énervé").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Cochon mutant énervé",
                zone:"terre-sauvage",
                attaque:10,
                parade:6,
                vie:30,
                armure:2,
                degats:"1D+4",
                experience:18,
                informations:"Poison : -1 Stats",
            },
            {
                code:("Brigand costaud").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Brigand costaud",
                zone:"terre-sauvage",
                attaque:10,
                parade:9,
                vie:22,
                armure:3,
                degats:"1D+3",
                experience:15,
                informations:"",
            },
            {
                code:("Ogre débile").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Ogre débile",
                zone:"terre-sauvage",
                attaque:8,
                parade:5,
                vie:40,
                armure:3,
                degats:"2D+3",
                experience:25,
                informations:"",
            },
            {
                code:("Troll berzerk débile").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Troll berzerk débile",
                zone:"terre-sauvage",
                attaque:8,
                parade:6,
                vie:45,
                armure:3,
                degats:"2D+4",
                experience:28,
                informations:"",
            },
            {
                code:("Ogre mutant débile").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Ogre mutant débile",
                zone:"terre-sauvage",
                attaque:8,
                parade:4,
                vie:45,
                armure:4,
                degats:"3D",
                experience:28,
                informations:"",
            },
            {
                code:("Auroch énervé").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Auroch énervé",
                zone:"terre-sauvage",
                attaque:11,
                parade:7,
                vie:40,
                armure:2,
                degats:"1D+6",
                experience:20,
                informations:"",
            },
            {
                code:("Troll géant maladroit").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Troll géant maladroit",
                zone:"terre-sauvage",
                attaque:7,
                parade:5,
                vie:50,
                armure:3,
                degats:"3D+2",
                experience:35,
                informations:"",
            },
            {
                code:("Brébiphant enragé").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Brébiphant enragé",
                zone:"terre-sauvage",
                attaque:8,
                parade:6,
                vie:45,
                armure:3,
                degats:"2D+2",
                experience:30,
                informations:"",
            },
            {
                code:("Guerrier maudit perdu").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Guerrier maudit perdu",
                zone:"terre-sauvage",
                attaque:12,
                parade:12,
                vie:40,
                armure:6,
                degats:"1D+6",
                experience:40,
                informations:"",
            },
            {
                code:("Orque élite sur sanglier").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Orque élite sur sanglier",
                zone:"terre-sauvage",
                attaque:12,
                parade:6,
                vie:40,
                armure:5,
                degats:"1D+6",
                experience:40,
                informations:"",
            },
            {
                code:("Hyppopogriffe").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Hyppopogriffe",
                zone:"terre-sauvage",
                attaque:8,
                parade:4,
                vie:70,
                armure:5,
                degats:"2D+4",
                experience:40,
                informations:"Parade impossible",
            },
            {
                code:("Grosse tarentule des cavernes").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Grosse tarentule des cavernes",
                zone:"terre-sauvage",
                attaque:12,
                parade:12,
                vie:30,
                armure:1,
                degats:"1D+6",
                experience:45,
                informations:"Poison : -1 Stats",
            },
            {
                code:("Nécrophage frénétique").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Nécrophage frénétique",
                zone:"terre-sauvage",
                attaque:12,
                parade:6,
                vie:40,
                armure:2,
                degats:"1D+6",
                experience:35,
                informations:"",
            },
            {
                code:("Scorpion géant").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Scorpion géant",
                zone:"terre-sauvage",
                attaque:12,
                parade:8,
                vie:30,
                armure:5,
                degats:"1D+6",
                experience:40,
                informations:"",
            },
            {
                code:("Morshleg à poil long").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Morshleg à poil long",
                zone:"terre-sauvage",
                attaque:6,
                parade:5,
                vie:72,
                armure:3,
                degats:"2D+2",
                experience:38,
                informations:"",
            },
            {
                code:("Millepattes monstrueux").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Millepattes monstrueux",
                zone:"terre-sauvage",
                attaque:12,
                parade:8,
                vie:40,
                armure:6,
                degats:"1D+6",
                experience:50,
                informations:"",
            },
            {
                code:("Dragon de banlieu adulte").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Dragon de banlieu adulte",
                zone:"terre-sauvage",
                attaque:13,
                parade:8,
                vie:65,
                armure:6,
                degats:"2D+8",
                experience:60,
                informations:"",
            },
        ];
    }

    static getMobForet(): Mob[]{
        return [
            {
                code:("Coccinelle berzerk").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Coccinelle berzerk",
                zone:"foret",
                attaque:15,
                parade:0,
                vie:0,
                armure:0,
                degats:"1",
                experience:2,
                informations:"Adresse pour l écraser",
            },
            {
                code:("Brigand de base").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Brigand de base",
                zone:"foret",
                attaque:9,
                parade:9,
                vie:18,
                armure:2,
                degats:"1D+2",
                experience:8,
                informations:"",
            },
            {
                code:("Globzoule").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Globzoule",
                zone:"foret",
                attaque:8,
                parade:4,
                vie:10,
                armure:1,
                degats:"1D",
                experience:8,
                informations:"Poison : -1 Stats",
            },
            {
                code:("Rat géant affamé").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Rat géant affamé",
                zone:"foret",
                attaque:9,
                parade:5,
                vie:10,
                armure:1,
                degats:"1D+1",
                experience:8,
                informations:"Poison : -1 Stats",
            },
            {
                code:("Castor mutant").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Castor mutant",
                zone:"foret",
                attaque:8,
                parade:4,
                vie:20,
                armure:1,
                degats:"1D+2",
                experience:10,
                informations:"Crache acide, si dégats -1 PR",
            },
            {
                code:("Brigand archer").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Brigand archer",
                zone:"foret",
                attaque:8,
                parade:6,
                vie:18,
                armure:2,
                degats:"1D+3",
                experience:10,
                informations:"11 AD",
            },
            {
                code:("Araignée tranchante").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Araignée tranchante",
                zone:"foret",
                attaque:9,
                parade:5,
                vie:18,
                armure:1,
                degats:"1D+2",
                experience:10,
                informations:"",
            },
            {
                code:("Chapon fanghien").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Chapon fanghien",
                zone:"foret",
                attaque:10,
                parade:6,
                vie:30,
                armure:2,
                degats:"1d+2",
                experience:10,
                informations:"",
            },
            {
                code:("Orque miteux").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Orque miteux",
                zone:"foret",
                attaque:9,
                parade:7,
                vie:15,
                armure:2,
                degats:"1D+4",
                experience:8,
                informations:"",
            },
            {
                code:("Brigand costaud").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Brigand costaud",
                zone:"foret",
                attaque:10,
                parade:9,
                vie:22,
                armure:3,
                degats:"1D+3",
                experience:15,
                informations:"",
            },
            {
                code:("Kobold de base").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Kobold de base",
                zone:"foret",
                attaque:16,
                parade:8,
                vie:15,
                armure:1,
                degats:"1D+2",
                experience:20,
                informations:"",
            },
            {
                code:("Sanglier noir fou").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Sanglier noir fou",
                zone:"foret",
                attaque:10,
                parade:6,
                vie:25,
                armure:2,
                degats:"1D+4",
                experience:16,
                informations:"Parade impossible",
            },
            {
                code:("Plante carnivore").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Plante carnivore",
                zone:"foret",
                attaque:10,
                parade:0,
                vie:30,
                armure:2,
                degats:"1D+2",
                experience:15,
                informations:"",
            },
            {
                code:("Ogre débile foret").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Ogre débile foret",
                zone:"foret",
                attaque:8,
                parade:5,
                vie:40,
                armure:3,
                degats:"2D+3",
                experience:25,
                informations:"",
            },
            {
                code:("Cochon mutant").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Cochon mutant",
                zone:"foret",
                attaque:10,
                parade:6,
                vie:30,
                armure:2,
                degats:"1D+4",
                experience:18,
                informations:"",
            },
            {
                code:("Panthère affamée").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Panthère affamée",
                zone:"foret",
                attaque:14,
                parade:4,
                vie:17,
                armure:1,
                degats:"1D+2",
                experience:20,
                informations:"",
            },
            {
                code:("Ogre mutant débilé foret").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Ogre mutant débilé foret",
                zone:"foret",
                attaque:8,
                parade:4,
                vie:45,
                armure:4,
                degats:"3D",
                experience:28,
                informations:"",
            },
            {
                code:("Troll berzerk débile foret").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Troll berzerk débile foret",
                zone:"foret",
                attaque:8,
                parade:6,
                vie:45,
                armure:3,
                degats:"2D+4",
                experience:28,
                informations:"",
            },
            {
                code:("Troll géant maladroit foret").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Troll géant maladroit foret",
                zone:"foret",
                attaque:7,
                parade:5,
                vie:50,
                armure:3,
                degats:"3D+2",
                experience:35,
                informations:"",
            },
            {
                code:("Dragon des cimes").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Dragon des cimes",
                zone:"foret",
                attaque:12,
                parade:9,
                vie:35,
                armure:5,
                degats:"1D+6",
                experience:30,
                informations:"",
            },
        ];
    }
    
    static getMobJungle(): Mob[]{
        return [
            {
                code:("Curupira").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Curupira",
                zone:"jungle",
                attaque:3,
                parade:0,
                vie:10,
                armure:0,
                degats:"1D",
                experience:2,
                informations:"Esquive 8",
            },
            {
                code:("Petit singe").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Petit singe",
                zone:"jungle",
                attaque:8,
                parade:8,
                vie:18,
                armure:0,
                degats:"1D+2",
                experience:8,
                informations:"",
            },
            {
                code:("Indigène agressif").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Indigène agressif",
                zone:"jungle",
                attaque:8,
                parade:8,
                vie:252,
                armure:2,
                degats:"1D+4",
                experience:12,
                informations:"",
            },
            {
                code:("Chaman agressif").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Chaman agressif",
                zone:"jungle",
                attaque:6,
                parade:6,
                vie:25,
                armure:1,
                degats:"0",
                experience:15,
                informations:"1/2 chance invoquer Jaguar",
            },
            {
                code:("Grand singe").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Grand sing",
                zone:"jungle",
                attaque:10,
                parade:10,
                vie:30,
                armure:1,
                degats:"1D+4",
                experience:18,
                informations:"",
            },
            {
                code:("Jaguar").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Jaguar",
                zone:"jungle",
                attaque:11,
                parade:11,
                vie:25,
                armure:1,
                degats:"1D+5",
                experience:25,
                informations:"",
            },
            {
                code:("Mapinguari").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Mapinguari",
                zone:"jungle",
                attaque:5,
                parade:5,
                vie:30,
                armure:3,
                degats:"3D+3",
                experience:30,
                informations:"",
            },
            {
                code:("Chupacabra").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Chupacabra",
                zone:"jungle",
                attaque:14,
                parade:14,
                vie:30,
                armure:2,
                degats:"2D+2",
                experience:35,
                informations:"",
            },
            {
                code:("Singe géant").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Singe géant",
                zone:"jungle",
                attaque:8,
                parade:8,
                vie:50,
                armure:5,
                degats:"2D+4",
                experience:40,
                informations:"",
            },
            {
                code:("Boiùna").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Boiùna",
                zone:"jungle",
                attaque:3,
                parade:0,
                vie:30,
                armure:5,
                degats:"1D+1",
                experience:50,
                informations:"Equive 5 . Imparable . Si dégats => 1 blessure ( stackable )",
            },
        ];
    }
    
    static getMobEst(): Mob[]{
        return [
            {
                code:("Chien sauvage").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Chien sauvage",
                zone:"est",
                attaque:6,
                parade:6,
                vie:15,
                armure:0,
                degats:"1D+2",
                experience:5,
                informations:"",
            },
            {
                code:("Kallikantzaroi").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Kallikantzaroi",
                zone:"est",
                attaque:7,
                parade:7,
                vie:15,
                armure:1,
                degats:"1D+2",
                experience:8,
                informations:"",
            },
            {
                code:("Tizheruk").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Tizheruk",
                zone:"est",
                attaque:9,
                parade:9,
                vie:20,
                armure:1,
                degats:"1D+3",
                experience:12,
                informations:"Poison : -1 Stats",
            },
            {
                code:("Mahaha").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Mahaha",
                zone:"est",
                attaque:11,
                parade:5,
                vie:20,
                armure:2,
                degats:"1D+4",
                experience:15,
                informations:"1/20 chance briser arme si paré",
            },
            {
                code:("Aigle électrique").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Aigle électrique",
                zone:"est",
                attaque:8,
                parade:8,
                vie:25,
                armure:2,
                degats:"1D+3",
                experience:18,
                informations:"Test AD nécessaire avant test AT",
            },
            {
                code:("Ogre à peau bleu").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Ogre à peau bleu",
                zone:"est",
                attaque:6,
                parade:6,
                vie:35,
                armure:4,
                degats:"2D+4",
                experience:25,
                informations:"",
            },
            {
                code:("Olsklül").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Olsklül",
                zone:"est",
                attaque:12,
                parade:12,
                vie:30,
                armure:2,
                degats:"1D+6",
                experience:30,
                informations:"",
            },
            {
                code:("Amarok").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Amarok",
                zone:"est",
                attaque:11,
                parade:11,
                vie:38,
                armure:3,
                degats:"1D+5",
                experience:30,
                informations:"",
            },
            {
                code:("Yeti").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Yeti",
                zone:"est",
                attaque:83,
                parade:8,
                vie:45,
                armure:4,
                degats:"3D+3",
                experience:40,
                informations:"",
            },
            {
                code:("Yukiona").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Yukiona",
                zone:"est",
                attaque:14,
                parade:14,
                vie:25,
                armure:4,
                degats:"1D+7",
                experience:50,
                informations:"Si touche ou touché, 1/2 chance de faire rater prochain assaut",
            },
        ];
    }
    
    static getMobMontagne(): Mob[]{
        return [
            {
                code:("Scarabée du désert").replaceAll(" ","-").replaceAll("'","-").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, ""),
                libelle: "Scarabée du désert",
                zone:"foret",
                attaque:15,
                parade:0,
                vie:0,
                informations:"On doit réussir une épreuve d’adresse pour l’écraser",
                degats:"1",
                armure:0,
                experience:2,
            },
        ];
    }
}
