export class Ville{
    "libelle":string;
    "region":string;
    "handicap":number;
    "malus" : Array<Malus>;
};

export class Malus{
    "region":string;
    "handicap":number;
}

export class VilleHelper{
    
    static getAllVilles():Array<Ville>{
 return [
    {
        "libelle":"Capitale",
        "region":"toutes",
        "handicap":0,
        "malus" : [
            {
                "region":"desert",
                "handicap":10
            },
            {
                "region":"nord",
                "handicap":25
            },
            {
                "region":"est",
                "handicap":40
            },
            {
                "region":"samurai",
                "handicap":60
            }
        ]
    },
    {
        "libelle":"Grande ville Commun",
        "region":"commune",
        "handicap":5,
        "malus" : [
            {
                "region":"desert",
                "handicap":15
            },
            {
                "region":"nord",
                "handicap":30
            },
            {
                "region":"est",
                "handicap":45
            },
            {
                "region":"samurai",
                "handicap":65
            }
        ]
    },
    {
        "libelle":"Grande ville Est",
        "region":"est",
        "handicap":5,
        "malus" : [
            {
                "region":"desert",
                "handicap":25
            },
            {
                "region":"nord",
                "handicap":45
            },
            {
                "region":"commune",
                "handicap":15
            },
            {
                "region":"samurai",
                "handicap":80
            }
        ]
    },
    {
        "libelle":"Grande ville Désert",
        "region":"desert",
        "handicap":10,
        "malus" : [
            {
                "region":"commune",
                "handicap":15
            },
            {
                "region":"nord",
                "handicap":30
            },
            {
                "region":"est",
                "handicap":45
            },
            {
                "region":"samurai",
                "handicap":65
            }
        ]
    },
    {
        "libelle":"Grande port Iles",
        "region":"ile",
        "handicap":10,
        "malus" : [
            {
                "region":"desert",
                "handicap":20
            },
            {
                "region":"nord",
                "handicap":40
            },
            {
                "region":"est",
                "handicap":65
            },
            {
                "region":"samurai",
                "handicap":65
            },
            {
                "region":"commune",
                "handicap":10
            }
        ]
    },
    {
        "libelle":"Grande ville Sud",
        "region":"sud",
        "handicap":10,
        "malus" : [
            {
                "region":"desert",
                "handicap":30
            },
            {
                "region":"nord",
                "handicap":40
            },
            {
                "region":"est",
                "handicap":75
            },
            {
                "region":"samurai",
                "handicap":65
            },
            {
                "region":"commune",
                "handicap":15
            }
        ]
    },
    {
        "libelle":"Grande ville Nord",
        "region":"nord",
        "handicap":10,
        "malus" : [
            {
                "region":"desert",
                "handicap":30
            },
            {
                "region":"commune",
                "handicap":25
            },
            {
                "region":"est",
                "handicap":85
            },
            {
                "region":"samurai",
                "handicap":85
            }
        ]
    },
    {
        "libelle":"Moyene ville Commun",
        "region":"commune",
        "handicap":10,
        "malus" : [
            {
                "region":"desert",
                "handicap":15
            },
            {
                "region":"nord",
                "handicap":30
            },
            {
                "region":"est",
                "handicap":45
            },
            {
                "region":"samurai",
                "handicap":65
            }
        ]
    },
    {
        "libelle":"Moyenne ville Est",
        "region":"est",
        "handicap":10,
        "malus" : [
            {
                "region":"desert",
                "handicap":25
            },
            {
                "region":"nord",
                "handicap":45
            },
            {
                "region":"commune",
                "handicap":15
            },
            {
                "region":"samurai",
                "handicap":80
            }
        ]
    },
    {
        "libelle":"Moyenne ville Désert",
        "region":"desert",
        "handicap":15,
        "malus" : [
            {
                "region":"commune",
                "handicap":15
            },
            {
                "region":"nord",
                "handicap":30
            },
            {
                "region":"est",
                "handicap":45
            },
            {
                "region":"samurai",
                "handicap":65
            }
        ]
    },
    {
        "libelle":"Moyenne port Iles",
        "region":"ile",
        "handicap":15,
        "malus" : [
            {
                "region":"desert",
                "handicap":20
            },
            {
                "region":"nord",
                "handicap":40
            },
            {
                "region":"est",
                "handicap":65
            },
            {
                "region":"samurai",
                "handicap":65
            },
            {
                "region":"commune",
                "handicap":10
            }
        ]
    },
    {
        "libelle":"Moyenne ville Sud",
        "region":"sud",
        "handicap":15,
        "malus" : [
            {
                "region":"desert",
                "handicap":30
            },
            {
                "region":"nord",
                "handicap":40
            },
            {
                "region":"est",
                "handicap":75
            },
            {
                "region":"samurai",
                "handicap":65
            },
            {
                "region":"commune",
                "handicap":15
            }
        ]
    },
    {
        "libelle":"Moyenne ville Nord",
        "region":"nord",
        "handicap":15,
        "malus" : [
            {
                "region":"desert",
                "handicap":30
            },
            {
                "region":"commune",
                "handicap":25
            },
            {
                "region":"est",
                "handicap":85
            },
            {
                "region":"samurai",
                "handicap":85
            }
        ]
    },
    {
        "libelle":"Petite ville Commun",
        "region":"commune",
        "handicap":15,
        "malus" : [
            {
                "region":"desert",
                "handicap":15
            },
            {
                "region":"nord",
                "handicap":30
            },
            {
                "region":"est",
                "handicap":45
            },
            {
                "region":"samurai",
                "handicap":65
            }
        ]
    },
    {
        "libelle":"Petite ville Est",
        "region":"est",
        "handicap":15,
        "malus" : [
            {
                "region":"desert",
                "handicap":25
            },
            {
                "region":"nord",
                "handicap":45
            },
            {
                "region":"commune",
                "handicap":15
            },
            {
                "region":"samurai",
                "handicap":80
            }
        ]
    },
    {
        "libelle":"Petite ville Désert",
        "region":"desert",
        "handicap":20,
        "malus" : [
            {
                "region":"commune",
                "handicap":15
            },
            {
                "region":"nord",
                "handicap":30
            },
            {
                "region":"est",
                "handicap":45
            },
            {
                "region":"samurai",
                "handicap":65
            }
        ]
    },
    {
        "libelle":"Petite port Iles",
        "region":"ile",
        "handicap":20,
        "malus" : [
            {
                "region":"desert",
                "handicap":20
            },
            {
                "region":"nord",
                "handicap":40
            },
            {
                "region":"est",
                "handicap":65
            },
            {
                "region":"samurai",
                "handicap":65
            },
            {
                "region":"commune",
                "handicap":10
            }
        ]
    },
    {
        "libelle":"Petite ville Sud",
        "region":"sud",
        "handicap":20,
        "malus" : [
            {
                "region":"desert",
                "handicap":30
            },
            {
                "region":"nord",
                "handicap":40
            },
            {
                "region":"est",
                "handicap":75
            },
            {
                "region":"samurai",
                "handicap":65
            },
            {
                "region":"commune",
                "handicap":15
            }
        ]
    },
    {
        "libelle":"Petite ville Nord",
        "region":"nord",
        "handicap":20,
        "malus" : [
            {
                "region":"desert",
                "handicap":30
            },
            {
                "region":"commune",
                "handicap":25
            },
            {
                "region":"est",
                "handicap":85
            },
            {
                "region":"samurai",
                "handicap":85
            }
        ]
    },
    {
        "libelle":"Bourgades, villages, hameaux Commun",
        "region":"commune",
        "handicap":20,
        "malus" : [
            {
                "region":"desert",
                "handicap":15
            },
            {
                "region":"nord",
                "handicap":30
            },
            {
                "region":"est",
                "handicap":45
            },
            {
                "region":"samurai",
                "handicap":65
            }
        ]
    },
    {
        "libelle":"Bourgades, villages, hameaux Est",
        "region":"est",
        "handicap":25,
        "malus" : [
            {
                "region":"desert",
                "handicap":25
            },
            {
                "region":"nord",
                "handicap":45
            },
            {
                "region":"commune",
                "handicap":15
            },
            {
                "region":"samurai",
                "handicap":80
            }
        ]
    },
    {
        "libelle":"Bourgades, villages, hameaux Désert",
        "region":"desert",
        "handicap":25,
        "malus" : [
            {
                "region":"commune",
                "handicap":15
            },
            {
                "region":"nord",
                "handicap":30
            },
            {
                "region":"est",
                "handicap":45
            },
            {
                "region":"samurai",
                "handicap":65
            }
        ]
    },
    {
        "libelle":"Bourgades, villages, hameaux Iles",
        "region":"ile",
        "handicap":30,
        "malus" : [
            {
                "region":"desert",
                "handicap":20
            },
            {
                "region":"nord",
                "handicap":40
            },
            {
                "region":"est",
                "handicap":65
            },
            {
                "region":"samurai",
                "handicap":65
            },
            {
                "region":"commune",
                "handicap":10
            }
        ]
    },
    {
        "libelle":"Bourgades, villages, hameaux Sud",
        "region":"sud",
        "handicap":30,
        "malus" : [
            {
                "region":"desert",
                "handicap":30
            },
            {
                "region":"nord",
                "handicap":40
            },
            {
                "region":"est",
                "handicap":75
            },
            {
                "region":"samurai",
                "handicap":65
            },
            {
                "region":"commune",
                "handicap":15
            }
        ]
    },
    {
        "libelle":"Bourgades, villages, hameaux Nord",
        "region":"nord",
        "handicap":30,
        "malus" : [
            {
                "region":"desert",
                "handicap":30
            },
            {
                "region":"commune",
                "handicap":25
            },
            {
                "region":"est",
                "handicap":85
            },
            {
                "region":"samurai",
                "handicap":85
            }
        ]
    },
    {
        "libelle":"Campement, fort Commun",
        "region":"commune",
        "handicap":8,
        "malus" : [
            {
                "region":"desert",
                "handicap":15
            },
            {
                "region":"nord",
                "handicap":30
            },
            {
                "region":"est",
                "handicap":45
            },
            {
                "region":"samurai",
                "handicap":65
            }
        ]
    },
    {
        "libelle":"Bourgades, villages, hameaux Est",
        "region":"est",
        "handicap":12,
        "malus" : [
            {
                "region":"desert",
                "handicap":25
            },
            {
                "region":"nord",
                "handicap":45
            },
            {
                "region":"commune",
                "handicap":15
            },
            {
                "region":"samurai",
                "handicap":80
            }
        ]
    },
    {
        "libelle":"Bourgades, villages, hameaux Désert",
        "region":"desert",
        "handicap":12,
        "malus" : [
            {
                "region":"commune",
                "handicap":15
            },
            {
                "region":"nord",
                "handicap":30
            },
            {
                "region":"est",
                "handicap":45
            },
            {
                "region":"samurai",
                "handicap":65
            }
        ]
    },
    {
        "libelle":"Bourgades, villages, hameaux Iles",
        "region":"ile",
        "handicap":15,
        "malus" : [
            {
                "region":"desert",
                "handicap":20
            },
            {
                "region":"nord",
                "handicap":40
            },
            {
                "region":"est",
                "handicap":65
            },
            {
                "region":"samurai",
                "handicap":65
            },
            {
                "region":"commune",
                "handicap":10
            }
        ]
    },
    {
        "libelle":"Bourgades, villages, hameaux Sud",
        "region":"sud",
        "handicap":15,
        "malus" : [
            {
                "region":"desert",
                "handicap":30
            },
            {
                "region":"nord",
                "handicap":40
            },
            {
                "region":"est",
                "handicap":75
            },
            {
                "region":"samurai",
                "handicap":65
            },
            {
                "region":"commune",
                "handicap":15
            }
        ]
    },
    {
        "libelle":"Bourgades, villages, hameaux Nord",
        "region":"nord",
        "handicap":15,
        "malus" : [
            {
                "region":"desert",
                "handicap":30
            },
            {
                "region":"commune",
                "handicap":25
            },
            {
                "region":"est",
                "handicap":85
            },
            {
                "region":"samurai",
                "handicap":85
            }
        ]
    }
];
    }
}