export class Ville{
    "libelle":string;
    "region":string;
    "handicap":number;
    "malus" : Array<Malus>;
};

export class Malus{
    "region":string;
    "handicap":number;
}

export class VilleHelper{
    
    static getAll():Array<Ville>{
 return [
    {
        "libelle":"Capitale",
        "region":"commune",
        "handicap":0,
        "malus" : [
            {
                "region":"desert",
                "handicap":10
            },
            {
                "region":"nord",
                "handicap":25
            },
            {
                "region":"est",
                "handicap":40
            },
            {
                "region":"samurai",
                "handicap":60
            }
        ]
    },
    {
        "libelle":"Commun - Grande ville",
        "region":"commune",
        "handicap":5,
        "malus" : [
            {
                "region":"desert",
                "handicap":15
            },
            {
                "region":"nord",
                "handicap":30
            },
            {
                "region":"est",
                "handicap":45
            },
            {
                "region":"samurai",
                "handicap":65
            }
        ]
    },
    {
        "libelle":"Est - Grande ville",
        "region":"est",
        "handicap":5,
        "malus" : [
            {
                "region":"desert",
                "handicap":25
            },
            {
                "region":"nord",
                "handicap":45
            },
            {
                "region":"commune",
                "handicap":15
            },
            {
                "region":"samurai",
                "handicap":80
            }
        ]
    },
    {
        "libelle":"Désert - Grande ville",
        "region":"desert",
        "handicap":10,
        "malus" : [
            {
                "region":"commune",
                "handicap":15
            },
            {
                "region":"nord",
                "handicap":30
            },
            {
                "region":"est",
                "handicap":45
            },
            {
                "region":"samurai",
                "handicap":65
            }
        ]
    },
    {
        "libelle":"Iles - Grande port",
        "region":"ile",
        "handicap":10,
        "malus" : [
            {
                "region":"desert",
                "handicap":20
            },
            {
                "region":"nord",
                "handicap":40
            },
            {
                "region":"est",
                "handicap":65
            },
            {
                "region":"samurai",
                "handicap":65
            },
            {
                "region":"commune",
                "handicap":10
            }
        ]
    },
    {
        "libelle":"Sud - Grande ville",
        "region":"sud",
        "handicap":10,
        "malus" : [
            {
                "region":"desert",
                "handicap":30
            },
            {
                "region":"nord",
                "handicap":40
            },
            {
                "region":"est",
                "handicap":75
            },
            {
                "region":"samurai",
                "handicap":65
            },
            {
                "region":"commune",
                "handicap":15
            }
        ]
    },
    {
        "libelle":"Nord - Grande ville",
        "region":"nord",
        "handicap":10,
        "malus" : [
            {
                "region":"desert",
                "handicap":30
            },
            {
                "region":"commune",
                "handicap":25
            },
            {
                "region":"est",
                "handicap":85
            },
            {
                "region":"samurai",
                "handicap":85
            }
        ]
    },
    {
        "libelle":"Commun - Moyenne ville",
        "region":"commune",
        "handicap":10,
        "malus" : [
            {
                "region":"desert",
                "handicap":15
            },
            {
                "region":"nord",
                "handicap":30
            },
            {
                "region":"est",
                "handicap":45
            },
            {
                "region":"samurai",
                "handicap":65
            }
        ]
    },
    {
        "libelle":"Est - Moyenne ville",
        "region":"est",
        "handicap":10,
        "malus" : [
            {
                "region":"desert",
                "handicap":25
            },
            {
                "region":"nord",
                "handicap":45
            },
            {
                "region":"commune",
                "handicap":15
            },
            {
                "region":"samurai",
                "handicap":80
            }
        ]
    },
    {
        "libelle":"Désert - Moyenne ville",
        "region":"desert",
        "handicap":15,
        "malus" : [
            {
                "region":"commune",
                "handicap":15
            },
            {
                "region":"nord",
                "handicap":30
            },
            {
                "region":"est",
                "handicap":45
            },
            {
                "region":"samurai",
                "handicap":65
            }
        ]
    },
    {
        "libelle":"Iles - Moyenne port",
        "region":"ile",
        "handicap":15,
        "malus" : [
            {
                "region":"desert",
                "handicap":20
            },
            {
                "region":"nord",
                "handicap":40
            },
            {
                "region":"est",
                "handicap":65
            },
            {
                "region":"samurai",
                "handicap":65
            },
            {
                "region":"commune",
                "handicap":10
            }
        ]
    },
    {
        "libelle":"Sud - Moyenne ville",
        "region":"sud",
        "handicap":15,
        "malus" : [
            {
                "region":"desert",
                "handicap":30
            },
            {
                "region":"nord",
                "handicap":40
            },
            {
                "region":"est",
                "handicap":75
            },
            {
                "region":"samurai",
                "handicap":65
            },
            {
                "region":"commune",
                "handicap":15
            }
        ]
    },
    {
        "libelle":"Nord - Moyenne ville",
        "region":"nord",
        "handicap":15,
        "malus" : [
            {
                "region":"desert",
                "handicap":30
            },
            {
                "region":"commune",
                "handicap":25
            },
            {
                "region":"est",
                "handicap":85
            },
            {
                "region":"samurai",
                "handicap":85
            }
        ]
    },
    {
        "libelle":"Commun - Petite ville",
        "region":"commune",
        "handicap":15,
        "malus" : [
            {
                "region":"desert",
                "handicap":15
            },
            {
                "region":"nord",
                "handicap":30
            },
            {
                "region":"est",
                "handicap":45
            },
            {
                "region":"samurai",
                "handicap":65
            }
        ]
    },
    {
        "libelle":"Est - Petite ville",
        "region":"est",
        "handicap":15,
        "malus" : [
            {
                "region":"desert",
                "handicap":25
            },
            {
                "region":"nord",
                "handicap":45
            },
            {
                "region":"commune",
                "handicap":15
            },
            {
                "region":"samurai",
                "handicap":80
            }
        ]
    },
    {
        "libelle":"Désert - Petite ville",
        "region":"desert",
        "handicap":20,
        "malus" : [
            {
                "region":"commune",
                "handicap":15
            },
            {
                "region":"nord",
                "handicap":30
            },
            {
                "region":"est",
                "handicap":45
            },
            {
                "region":"samurai",
                "handicap":65
            }
        ]
    },
    {
        "libelle":"Iles - Petite port",
        "region":"ile",
        "handicap":20,
        "malus" : [
            {
                "region":"desert",
                "handicap":20
            },
            {
                "region":"nord",
                "handicap":40
            },
            {
                "region":"est",
                "handicap":65
            },
            {
                "region":"samurai",
                "handicap":65
            },
            {
                "region":"commune",
                "handicap":10
            }
        ]
    },
    {
        "libelle":"Sud - Petite ville",
        "region":"sud",
        "handicap":20,
        "malus" : [
            {
                "region":"desert",
                "handicap":30
            },
            {
                "region":"nord",
                "handicap":40
            },
            {
                "region":"est",
                "handicap":75
            },
            {
                "region":"samurai",
                "handicap":65
            },
            {
                "region":"commune",
                "handicap":15
            }
        ]
    },
    {
        "libelle":"Nord - Petite ville",
        "region":"nord",
        "handicap":20,
        "malus" : [
            {
                "region":"desert",
                "handicap":30
            },
            {
                "region":"commune",
                "handicap":25
            },
            {
                "region":"est",
                "handicap":85
            },
            {
                "region":"samurai",
                "handicap":85
            }
        ]
    },
    {
        "libelle":"Commun - Bourgades, villages, hameaux",
        "region":"commune",
        "handicap":20,
        "malus" : [
            {
                "region":"desert",
                "handicap":15
            },
            {
                "region":"nord",
                "handicap":30
            },
            {
                "region":"est",
                "handicap":45
            },
            {
                "region":"samurai",
                "handicap":65
            }
        ]
    },
    {
        "libelle":"Est - Bourgades, villages, hameaux",
        "region":"est",
        "handicap":25,
        "malus" : [
            {
                "region":"desert",
                "handicap":25
            },
            {
                "region":"nord",
                "handicap":45
            },
            {
                "region":"commune",
                "handicap":15
            },
            {
                "region":"samurai",
                "handicap":80
            }
        ]
    },
    {
        "libelle":"Désert - Bourgades, villages, hameaux",
        "region":"desert",
        "handicap":25,
        "malus" : [
            {
                "region":"commune",
                "handicap":15
            },
            {
                "region":"nord",
                "handicap":30
            },
            {
                "region":"est",
                "handicap":45
            },
            {
                "region":"samurai",
                "handicap":65
            }
        ]
    },
    {
        "libelle":"Iles - Bourgades, villages, hameaux",
        "region":"ile",
        "handicap":30,
        "malus" : [
            {
                "region":"desert",
                "handicap":20
            },
            {
                "region":"nord",
                "handicap":40
            },
            {
                "region":"est",
                "handicap":65
            },
            {
                "region":"samurai",
                "handicap":65
            },
            {
                "region":"commune",
                "handicap":10
            }
        ]
    },
    {
        "libelle":"Sud - Bourgades, villages, hameaux",
        "region":"sud",
        "handicap":30,
        "malus" : [
            {
                "region":"desert",
                "handicap":30
            },
            {
                "region":"nord",
                "handicap":40
            },
            {
                "region":"est",
                "handicap":75
            },
            {
                "region":"samurai",
                "handicap":65
            },
            {
                "region":"commune",
                "handicap":15
            }
        ]
    },
    {
        "libelle":"Nord - Bourgades, villages, hameaux",
        "region":"nord",
        "handicap":30,
        "malus" : [
            {
                "region":"desert",
                "handicap":30
            },
            {
                "region":"commune",
                "handicap":25
            },
            {
                "region":"est",
                "handicap":85
            },
            {
                "region":"samurai",
                "handicap":85
            }
        ]
    },
    {
        "libelle":"Commun - Campement, fort",
        "region":"commune",
        "handicap":8,
        "malus" : [
            {
                "region":"desert",
                "handicap":15
            },
            {
                "region":"nord",
                "handicap":30
            },
            {
                "region":"est",
                "handicap":45
            },
            {
                "region":"samurai",
                "handicap":65
            }
        ]
    },
    {
        "libelle":"Est - Bourgades, villages, hameaux",
        "region":"est",
        "handicap":12,
        "malus" : [
            {
                "region":"desert",
                "handicap":25
            },
            {
                "region":"nord",
                "handicap":45
            },
            {
                "region":"commune",
                "handicap":15
            },
            {
                "region":"samurai",
                "handicap":80
            }
        ]
    },
    {
        "libelle":"Désert - Bourgades, villages, hameaux",
        "region":"desert",
        "handicap":12,
        "malus" : [
            {
                "region":"commune",
                "handicap":15
            },
            {
                "region":"nord",
                "handicap":30
            },
            {
                "region":"est",
                "handicap":45
            },
            {
                "region":"samurai",
                "handicap":65
            }
        ]
    },
    {
        "libelle":"Iles - Bourgades, villages, hameaux",
        "region":"ile",
        "handicap":15,
        "malus" : [
            {
                "region":"desert",
                "handicap":20
            },
            {
                "region":"nord",
                "handicap":40
            },
            {
                "region":"est",
                "handicap":65
            },
            {
                "region":"samurai",
                "handicap":65
            },
            {
                "region":"commune",
                "handicap":10
            }
        ]
    },
    {
        "libelle":"Sud - Bourgades, villages, hameaux",
        "region":"sud",
        "handicap":15,
        "malus" : [
            {
                "region":"desert",
                "handicap":30
            },
            {
                "region":"nord",
                "handicap":40
            },
            {
                "region":"est",
                "handicap":75
            },
            {
                "region":"samurai",
                "handicap":65
            },
            {
                "region":"commune",
                "handicap":15
            }
        ]
    },
    {
        "libelle":"Nord - Bourgades, villages, hameaux",
        "region":"nord",
        "handicap":15,
        "malus" : [
            {
                "region":"desert",
                "handicap":30
            },
            {
                "region":"commune",
                "handicap":25
            },
            {
                "region":"est",
                "handicap":85
            },
            {
                "region":"samurai",
                "handicap":85
            }
        ]
    }
];
    }
}